### PR TITLE
Fix encoding problems

### PR DESCRIPTION
**Pull request by jvoigtlaender**
I hope this will fix the "invalid argument (invalid character)" problems coming from utf8 use once and for all. It does fix https://github.com/elm-lang/elm-make/issues/33 and https://github.com/elm-lang/elm-make/issues/40, and probably all alike issues as well.

As a concrete example, on my Windows machine, the following happens both with Elm 0.16 installed by the Win installer and with Elm 0.16 compiled from source:
```
> elm-package install evancz/elm-markdown --yes
... everything fine
> elm-make test.elm
Success! Compiled 38 modules.
elm-make.exe: index.html: commitAndReleaseBuffer: invalid argument (invalid character)
> elm-make test.elm
Success! Compiled 0 modules.
elm-make.exe: index.html: commitAndReleaseBuffer: invalid argument (invalid character)
```
where `test.elm` is the file `HelloWorld4.elm` from http://elm-by-example.org/chapter1helloworld.html (but that doesn't really matter, the problem is not in that file).

Now after the pull request here is applied, and `elm-make` is recompiled from source, the following happens instead:
```
> elm-make test.elm
Success! Compiled 0 modules.
Successfully generated index.html
```
So #40 is fixed.

For #33, I checked the example program
```elm
import Graphics.Element exposing (..)

main : Element
main = show "私"
```
given there. Again, the current 0.16 `elm-make` chokes on that, but the compiled-from-source `elm-make` with this pull request applied works just fine!

Probably other Elm tools (beside `elm-make`) should get the same treatment.

@evancz, @rtfeldman

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
I have created corresponding pull requests for `elm-compiler`, `elm-package`, `elm-repl`, and `elm-reactor`.

**Comment by donutcho** [comment]
WATCHING!

**Comment by evancz** [comment]
What exactly is `setLocaleEncoding` doing behind the scenes? I looked through the source and couldn't really figure it out.

The key question is: is this just temporary for the life of the execution in Haskell? Or are we setting something on the user's computer permanently?

**Comment by jvoigtlaender** [comment]
It's not setting something on the computer permanently. Not even for the life of the shell session. Only for the life of the program.

At least that's the case on Windows, where I've tested this extensively.

**Comment by jvoigtlaender** [comment]
@evancz, have I answered your "key question" above?

**Comment by evancz** [comment]
I merged this in. I don't understand what is wrong with GitHub at the moment, but it's not showing up here.

You answered it, but avoided the question about what is happening behind the scenes. I did additional research to try to figure it out. Still not sure.

**Comment by evancz** [comment]
Please do not try to get #33 and #40 closed until I have an alpha of 0.17 out. I do not want people building from source until I have properly documented what is going on there.

**Comment by jvoigtlaender** [comment]
Okay, thanks for the heads up.

**Pull request closed without merging**
