### PR TITLE
CommonJS/Node/AMD snippet to end of compiled output

### PR DESCRIPTION
**Pull request by itrelease**

### CODE REVIEW

**Comment by rtfeldman** [comment]
Nice! :smiley:

**Comment by zigomir** [comment]
If I understand this correctly, this means one could use `require` or `import` to get Elm code into JS build? That would be great!

**Comment by itrelease** [comment]
@zigomir yeah that's exactly the point also it would be possible to require it in nodejs env and then you can try to mock some objects (document, navigator...) to render app on server-side

**Comment by etaque** [comment]
Just ran into a case where that PR would be very useful: an Elm component wrapped in JS, to be distributed as a toolkit.

**Comment by Wildhoney** [comment]
What's the current state of transpiling Elm to CommonJS code? Are still dependent on the merging of this PR?

**Comment by evancz** [comment]
Thanks for the PR. I am going to add this on my own though.

**Pull request closed without merging**
